config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup'  => 'users#new'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :email_verifications, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]

  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@([a-z\d\-]+\.)*([a-z]+)\z/i
  attr_accessor :remember_token, :verification_token, :reset_token

  before_create :create_verification
  before_save :downcase_email

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  has_many :microposts, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  # Returns the hash digest of the given string.
  def self.digest(string)
    if ActiveModel::SecurePassword.min_cost
      cost = BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(token_type, token)
    digest = send "#{token_type}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def verify_email
    update_columns(verified: true, verified_at: Time.zone.now)
  end

  # Sends activation email.
  def send_verification_email
    UserMailer.email_verification(self).deliver_now
  end

  # Sends activation email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Creates the password reset token
  def create_password_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  def reset_token_expired?
    # for time, '<' is means 'earlier than'
    reset_sent_at && reset_sent_at < 2.hours.ago
  end

  # get all of this user's microposts
  def feed
    following_ids = 'SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id'

    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id",
                    user_id: id)
  end

  # follow a user
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include? user
  end

  private

  # Creates the verification token
  def create_verification
    self.verification_token = User.new_token
    self.verification_digest = User.digest(verification_token)
  end

  # normalize emails
  def downcase_email
    email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]
  before_action :user_show_acl,  only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_verification_email
      show_signup_feedback @user
      log_in @user
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def index
    if current_user.verified?
      if @current_user.admin?
        @users = User.paginate(page: params[:page])
      else
        # only show verified users to non-admins
        @users = User.where(verified: true).paginate(page: params[:page])
      end
    else
      permission_denied
    end
  end

  def show
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Changes saved.'
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    user = User.find(params[:id])
    name = user.name
    user.destroy

    flash[:success] = "User '#{name}' deleted"

    redirect_to users_url
  end

  def following
    @user = User.find_by(id: params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @user = User.find_by(id: params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def new_user_info_flash(user)
    verify_link = edit_email_verification_path(user.verification_token,
                                               email: user.email)
    ". <a class=\"v_link\" href=\"#{verify_link}\">dev verify</a>" \
    " token: '<span class=\"v_token\">#{user.verification_token}</span>'" \
    " id: '<span class=\"user_id\">#{user.id}</span>'"
  end

  def show_signup_feedback(user)
    message = "Welcome, #{user.name}! Please check your email to verify it"

    message += new_user_info_flash user if Rails.env.development?

    flash[:success] = message
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user_is @user
  end

  def permission_denied
    flash[:danger] = 'Sorry, you don\'t have permission to do that'
    redirect_to(@current_user.verified? ? users_path : root_path)
  end

  # Confirms admins only
  def admin_user
    permission_denied unless current_user.admin?
  end

  def user_show_acl
    @user = User.find(params[:id])
    return if @user && (
      @user.verified? || current_user.admin? || @user == current_user)

    flash[:danger] = "Sorry, user '#{params[:id]}' does not exist"
    redirect_to users_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{size}"
    image_tag url, alt: user.name, class: 'gravatar'
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user, class: 'js-user-profile-link' %>
  <span class='badge microposts-count'><%= user.microposts.count %></span>
  <% if current_user.admin? && !current_user_is(user) %>
    | <%= link_to "delete", user, method: :delete, class: 'js-delete-user',
          data: { confirm: "Are you sure you want to delete the user '#{user.name}'?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes')%>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
<% @users.each do |user| %>
  <%= render user %>
<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:button_text, 'Create my Account')%>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <% # TODO: move this into the user_info partial %>
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <span id='user_name'><%= @user.name %></span>
      </h1>
      <span class='badge microposts-count'><%= @user.microposts.count %></span>
      <% if current_user == @user %>
        <%= link_to "Edit", edit_user_path(current_user) %>
      <% end %>
      <%= render 'shared/user_follower_stats' %>
    </section>
    <% if @user == current_user %>
      <%= render 'shared/micropost_form' %>
    <% end %>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% # TODO: merge this with the feed partial %>
    <% if @microposts.any? %>
      <h3>Microposts by <%= @user.name %></h3>
      <ol class="microposts">
        <% @microposts.each do |micropost| %>
          <%= render micropost %>
        <% end %>
      </ol>
      <%= will_paginate @microposts %>
    <% else %>
      <span class="microposts">
        <%= @user.name %> hasn't posted anything yet!
      </span>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/user_follower_stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %>
          <%= render user %>
        <% end %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>